# Generated by Django 4.2.7 on 2025-05-29 23:51

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_tokenhistory_never_expires_user_token_never_expires_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "daily_request_limit",
                    models.IntegerField(help_text="Daily API request limit"),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly price in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Price ID for this plan",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "features",
                    models.JSONField(default=dict, help_text="Additional features for this plan"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["price_monthly"],
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="daily_request_limit",
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("trialing", "Trialing"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Current subscription plan",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.plan",
            ),
        ),
    ]
