# Generated by Django 5.2.1 on 2025-05-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20250529_2051"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="current_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
