# Generated by Django 5.2.1 on 2025-06-03 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_add_waiting_list"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
