# Generated by Django 5.2.1 on 2025-06-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="daily_requests_made",
            field=models.IntegerField(default=0),
        ),
    ]
