# Generated by Django 5.2.1 on 2025-07-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_apiusage_paymentfailure_ratelimitcounter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="payment_failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="payment_restrictions_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="PaymentFailure",
        ),
    ]
