# Generated by Django 5.2.1 on 2025-07-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_apiusage_paymentfailure_ratelimitcounter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_restriction_level',
            field=models.CharField(choices=[('UNRESTRICTED', 'Unrestricted'), ('warning', 'Warning'), ('limited_access', 'Limited Access'), ('suspicious', 'Suspicious')], default='UNRESTRICTED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_restrictions_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PaymentFailure',
        ),
    ]
