# Generated by Django 5.2.1 on 2025-07-26 00:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_feature_remove_plan_features_plan_features"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apiusage",
            name="users_apius_user_id_14e7ee_idx",
        ),
        migrations.RemoveIndex(
            model_name="apiusage",
            name="users_apius_user_id_2ab62d_idx",
        ),
        migrations.RemoveIndex(
            model_name="apiusage",
            name="users_apius_date_b54a12_idx",
        ),
        migrations.RemoveIndex(
            model_name="apiusage",
            name="users_apius_user_id_f70bbd_idx",
        ),
        migrations.RemoveIndex(
            model_name="apiusage",
            name="users_apius_ip_addr_06f1fc_idx",
        ),
    ]
