# Generated by Django 4.2.7 on 2025-07-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_plan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglist",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10 employees"),
                    ("11-50", "11-50 employees"),
                    ("51-200", "51-200 employees"),
                    ("201-500", "201-500 employees"),
                    ("501-1000", "501-1000 employees"),
                    ("1000+", "1000+ employees"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="waitinglist",
            name="desired_endpoints",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
