# Generated by Django 4.2.7 on 2025-07-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_waitinglist_company_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglist",
            name="desired_plan",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
