# Generated by Django 4.2.7 on 2025-07-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_waitinglist_desired_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglist",
            name="desired_billing_cycle",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                max_length=10,
            ),
        ),
    ]
