from __future__ import annotations

from django.urls import path

from .views_polygon import (
    AggCustomRangeView,
    AggGroupedDailyView,
    AggPreviousDayView,
    IndicatorEMAView,
    IndicatorMACDView,
    IndicatorRSIView,
    IndicatorSMAView,
    LastNBBOView,
    LastTradeView,
    MarketHolidaysView,
    MarketStatusView,
    OpenCloseView,
    QuotesView,
    ReferenceConditionsView,
    ReferenceDividendsView,
    ReferenceExchangesView,
    ReferenceFinancialsView,
    ReferenceIPOsView,
    ReferenceNewsView,
    ReferenceSplitsView,
    ReferenceTickerEventsView,
    ReferenceTickerTypesView,
    ReferenceTickerView,
    ReferenceTickersView,
    RelatedCompaniesView,
    SnapshotMarketView,
    SnapshotMoversView,
    SnapshotTickerView,
    SnapshotUnifiedView,
    StocksShortInterestView,
    StocksShortVolumeView,
    TradesView,
)


urlpatterns = [
    AggCustomRangeView.as_path(),
    AggGroupedDailyView.as_path(),
    AggPreviousDayView.as_path(),
    IndicatorEMAView.as_path(),
    IndicatorMACDView.as_path(),
    IndicatorRSIView.as_path(),
    IndicatorSMAView.as_path(),
    LastNBBOView.as_path(),
    LastTradeView.as_path(),
    MarketHolidaysView.as_path(),
    MarketStatusView.as_path(),
    OpenCloseView.as_path(),
    QuotesView.as_path(),
    ReferenceConditionsView.as_path(),
    ReferenceDividendsView.as_path(),
    ReferenceExchangesView.as_path(),
    ReferenceFinancialsView.as_path(),
    ReferenceIPOsView.as_path(),
    ReferenceNewsView.as_path(),
    ReferenceSplitsView.as_path(),
    ReferenceTickerEventsView.as_path(),
    ReferenceTickerTypesView.as_path(),
    ReferenceTickerView.as_path(),
    ReferenceTickersView.as_path(),
    RelatedCompaniesView.as_path(),
    SnapshotMarketView.as_path(),
    SnapshotMoversView.as_path(),
    SnapshotTickerView.as_path(),
    SnapshotUnifiedView.as_path(),
    StocksShortInterestView.as_path(),
    StocksShortVolumeView.as_path(),
    TradesView.as_path(),
]


